CREATE TABLE ingredients (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
--;;
insert  into ingredients(id,name) values
(1,'Baking spray with flour'),
(2,'All-purpose flour '),
(3,'Sugar '),
(4,'Baking powder '),
(5,'Cinnamon '),
(6,'Milk'),
(7,'Butter'),
(8,'Vanilla extract'),
(9,'Eggs'),
(10,'Raspberries'),
(11,'Orange'),
(12,'Banana'),
(13,'Porridge oats'),
(14,'Chia seeds'),
(15,'Potato'),
(16,'Salt'),
(17,'Pepper'),
(18,'Cheddar cheese'),
(19,'Onion'),
(20,'Parmesan cheese'),
(21,'Pea pods'),
(22,'Peas'),
(23,'Unsalted butter'),
(24,'Shallot'),
(25,'Arborio rice'),
(26,'Lemon'),
(27,'Olive oil'),
(28,'Dry white wine'),
(29,'Basil'),
(30,'Parsley'),
(31,'Garilc'),
(32,'Spinach'),
(33,'Zucchini'),
(34,'Shrimp '),
(35,'Tomato'),
(36,'Corn'),
(37,'Tortilla'),
(38,'Tuna'),
(39,'Avocado'),
(40,'Brown sugar'),
(41,'Baking soda'),
(42,'Chocolate chips');