CREATE TABLE recipe (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  description varchar(5000) DEFAULT NULL,
  recipe_type int(11) DEFAULT NULL,
  user int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY recipe_type (recipe_type),
  KEY user (user),
  CONSTRAINT recipe_ibfk_1 FOREIGN KEY (recipe_type) REFERENCES recipe_type (id),
  CONSTRAINT recipe_ibfk_2 FOREIGN KEY (user) REFERENCES user (id)
);
--;;
insert  into recipe(id,name,description,recipe_type,user) values
(1,'Cinnamon Baked Doughnuts','Preheat the oven to 350 degrees. Spray 2 doughnut pans well.\r\nInto a large bowl, sift together the flour, sugar, baking powder, cinnamon, nutmeg, and salt. In a small bowl, whisk together the egg, milk, melted butter, and vanilla. Stir the wet mixture into the dry ingredients until just combined.\r\nSpoon the batter into the baking pans, filling each one a little more than three-quarters full. Bake for 17 minutes, until a toothpick comes out clean. Allow to cool for 5 minutes, then tap the doughnuts out onto a sheet pan.\r\nFor the topping, melt the 8 tablespoons of butter in an 8-inch saute pan. Combine the sugar and cinnamon in a small bowl. Dip each doughnut first in the butter and then in the cinnamon sugar, either on one side or both sides.',1,1),
(2,'Healthy porridge bowl','Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins.\r\n\r\nMeanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.',1,1),
(3,' Sheepherder’s Breakfast','In a large skillet, cook bacon and onion over medium heat until bacon is crisp. Drain, reserving 1/4 cup drippings in pan.\r\nStir in hash browns. Cook, uncovered, over medium heat until bottom is golden brown, about 10 minutes. Turn potatoes. With the back of a spoon, make 8 evenly spaced wells in potato mixture. Break 1 egg into each well. Sprinkle with salt and pepper.\r\nCook, covered, on low until eggs are set and potatoes are tender, about 10 minutes. Sprinkle with cheese; let stand until cheese is melted.',1,1),
(4,'Sweet Pea Risotto','Grate Parmesan into small bowl and set aside; transfer rind to small pot. Add pea pods (or 1 cup frozen peas) and 5 cups water; bring to a boil, then simmer 10 minutes. Strain, discard solids and return pea stock to pot; keep warm on low. In blender, puree 1 cup each peas and pea stock until smooth. \r\nMelt 2 tablespoons butter in large saucepan on medium. Add shallot and 1/4 teaspoon salt and cook until tender, about 2 minutes.\r\nAdd rice and cook, stirring to coat and toast, about 5 minutes. Add wine and simmer until nearly evaporated, 2 to 3 minutes.\r\nAdd stock, 3/4 cup at a time, stirring often until nearly absorbed before adding more. Stir in pea puree and simmer until rice is nearly tender, about 5 minutes. Stir in remaining peas. \r\nRemove risotto from heat. Finely grate zest of lemon and squeeze juice from 1 lemon half into risotto, then stir in grated Parmesan and remaining 2 tablespoons butter.\r\nSqueeze juice of remaining lemon half into bowl; toss with pea shoots, olive oil and salt and pepper to taste. Serve over risotto.',2,1),
(5,'Spinach & Gruyère Potato Casserole','Preheat oven to 450 degrees F. Toss potatoes with oil and 1/4 teaspoon each salt and pepper; arrange in single layer on rimmed baking sheet. Bake 20 to 25 minutes or until golden brown and tender. Reduce oven temperature to 375 degrees F.\r\nMeanwhile, whisk together eggs, half-and-half and 1/2 teaspoon salt; stir in Gruyère, basil, parsley and garlic. In large bowl, toss potatoes, spinach and fennel with egg mixture until well combined. Transfer to 2-quart. baking dish; cover with foil.\r\nBake 30 to 35 minutes or until custard has set. Uncover; bake another 5 minutes. Garnish with additional basil and parsley, if desired.',2,1),
(6,'Grilled Leek Potato Salad','Heat grill to medium-high. Place potatoes in large pot, add enough cold water to cover by 2 inches, and bring to a boil. Add 2 teaspoons salt, reduce heat, and simmer until just tender, 12 to 15 minutes. Drain and run under cold water to cool. \r\nWhile potatoes cook, brush leeks with 2 teaspoons oil, then place on grill cut sides down and grill, covered, until charred and nearly tender, 6 minutes. Turn and cook 2 minutes more. Transfer to bowl, cover with plastic wrap, and let sit at least 5 minutes.\r\nMeanwhile, in large bowl, combine lemon zest, pepper flakes, vinegar, mustard, remaining 3 tablespoons oil, and 1/2 teaspoon each salt and pepper. \r\nHalve potatoes, or quarter if large. Chop leeks and toss with vinaigrette, then fold in potatoes.',2,1),
(7,'15 Minute Garlic Shrimp Zoodles','Spiralize the zucchini on the medium setting. Set aside.\r\nAdd the olive oil and lemon juice & zest to a skillet on medium heat. Once the pan is warm, add the shrimp. Cook the shrimp for one minute per side.\r\nAdd the garlic and red pepper flakes. Cook for an additional minute, stirring often.\r\nAdd the zucchini noodles and stir/toss (e.g. with tongs) constantly for 2-3 minutes until they\'re slightly cooked and warmed up.\r\nSeason with salt and pepper and sprinkle with the chopped parlsey. Serve immediately.',3,1),
(8,'Avocado Tuna Salad','Place all of the ingredients in a medium bowl. Mix with a fork or spoon until the avocado is roughly mashed and mixed through.\r\nServe on lettuce wraps, toast, or in a sandwich. To store, cover tightly with plastic wrap and refrigerate for up to 2 days.',3,1),
(9,'The Best Chocolate Chip Cookie','Preheat oven to 375 degrees F. Line a baking pan with parchment paper and set aside.\r\nIn a separate bowl mix flour, baking soda, salt, baking powder. Set aside.\r\nCream together butter and sugars until combined.\r\nBeat in eggs and vanilla until fluffy.\r\nMix in the dry ingredients until combined.\r\nAdd 12 oz package of chocolate chips and mix well.\r\nRoll 2-3 TBS (depending on how large you like your cookies) of dough at a time into balls and place them evenly spaced on your prepared cookie sheets. (alternately, use a small cookie scoop to make your cookies).\r\nBake in preheated oven for approximately 8-10 minutes. Take them out when they are just BARELY starting to turn brown.\r\nLet them sit on the baking pan for 2 minutes before removing to cooling rack.',4,1);
